E2Helper.Descriptions["isValid(xcr:)"] = "Returns 1 if the contraption is valid and 0 otherwise."
E2Helper.Descriptions["getContraption(e:)"] = "Returns the contraption constrained to this entity."
E2Helper.Descriptions["count(xcr:)"] = "Returns the number of entities in the contraption."
E2Helper.Descriptions["getMass(xcr:)"] = "Returns the total mass of the contraption in kg."
E2Helper.Descriptions["getTable(xcr:)"] = "Returns the E2 table of the contraption."
E2Helper.Descriptions["getEntities(xcr:)"] = "Returns the entities contained in the contraption."