name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: CFC-Servers/gmod-upload@master
        with:
          id: 3154971187
          changelog: "${{ github.event.head_commit.message }}"
          title: "Contraption Framework"
          type: "tool"
          tag1: "build"
        env:
          STEAM_USERNAME: ${{ secrets.ACF_STEAM_ACCOUNT }}
          STEAM_PASSWORD: ${{ secrets.ACF_STEAM_PASSWORD }}
